# Understanding the `numpy.ndarray` internals

In [1]:
import numpy as np

In [33]:
x = np.array([[0, 1, 2, 3],[4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]], dtype=np.int8)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]], dtype=int8)

In [34]:
x.strides

(4, 1)

***
### 1. Understanding strides
<mark>Question</mark>: Determine the strides for the following arrays. Check your answer with `x.strides`.

In [35]:
# 1.1
y = x.reshape((2, 8))
y
print(y.strides)
y

(8, 1)


array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]], dtype=int8)

In [36]:
# 1.2
z = x.reshape((1, 16))
print(z.strides)
print(z)

(16, 1)
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]


In [37]:
# 1.3
a = np.array([[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11], [12, 13, 14, 15]], dtype=np.int16)
print(a)
print(a.strides)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
(8, 2)


***
### 2. Metadata modification vs copying the data buffer

<mark>Question</mark>: How do you explain the next result? Is the result the same when using `x.flatten()` instead of `x.ravel()`?

> Note: Both `flatten()` and `ravel()` return a flattend version of an array.

In [38]:
x = np.arange(5)
print('x =', x)

y = x.ravel()  #  assign to y a flattened version the array x
y[0] = 5       #  change the first element of the array y

print('\nx =', x)

x = [0 1 2 3 4]

x = [5 1 2 3 4]


<mark>Question</mark>: The next three cells do the same two operations: transposing a matrix and flattening it. How do you explain the difference in execution time?

In [39]:
x = np.random.rand(5000, 5000)

In [46]:
%%timeit
# 2.1
x.T
x.ravel()

215 ns ± 9.44 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [47]:
%%timeit
# 2.2
x.T
x.flatten()

106 ms ± 1.01 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [50]:
%%timeit
# 2.3
x.T.flatten()

276 ms ± 8.44 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [51]:
%%timeit
# 2.3
x.T.ravel()

275 ms ± 4.68 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
