# Introduction to NumPy
The NumPy package provides the "ndarray" object. The NumPy array is used to contain data of uniform type with an arbitrary number of dimensions. NumPy then provides basic mathematical and array methods to lay down the foundation for the entire SciPy ecosystem. The following import statement is the generally accepted convention for NumPy.

In [2]:
import numpy as np

## Array Creation
There are several ways to make NumPy arrays. An array has three particular attributes that can be queried: shape, size and the number of dimensions.

In [16]:
a = np.array([1, 2, 3])
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)
print(type(a))
print(a.nbytes)  # Return the number of bytes used by the data portion of the array

(3,)
3
1
int64
<class 'numpy.ndarray'>
24


In [15]:
x = np.arange(100)
print(x.shape)
print(x.size)
print(x.ndim)
print(x.dtype)
print(type(x))
print(x.nbytes)

(100,)
100
1
int64
<class 'numpy.ndarray'>
800


In [14]:
y = np.random.rand(5, 80)
print(y.shape)
print(y.size)
print(y.ndim)
print(y.dtype)
print(type(y))

(5, 80)
400
2
float64
<class 'numpy.ndarray'>


## Array Operations

In [78]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])
a + b

array([3, 5, 7, 9])

In [79]:
a*b

array([ 2,  6, 12, 20])

In [80]:
a**b

array([   1,    8,   81, 1024])

## Math functions

In [114]:
# create array from 0. to 10.
x = np.arange(11)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [115]:
# multply entire array by scalar value
c = 2*np.pi/10

# print
print('c', c)
print(f'c = {c}') # f strings
print('c*x = ', c*x)
print(f'{c*x = }')
print(f'c*x = {c*x}')
print(f'{(c*x).round(3)}')

y = 0.8
print(f'{np.cos(y) = :.2f}')
print(f'{np.cos(y):.2f}')
print(f'{np.cos(y).round(3)}')


c 0.6283185307179586
c = 0.6283185307179586
c*x =  [0.    0.628 1.257 1.885 2.513 3.142 3.77  4.398 5.027 5.655 6.283]
c*x = array([0.   , 0.628, 1.257, 1.885, 2.513, 3.142, 3.77 , 4.398, 5.027,
       5.655, 6.283])
c*x = [0.    0.628 1.257 1.885 2.513 3.142 3.77  4.398 5.027 5.655 6.283]
[0.    0.628 1.257 1.885 2.513 3.142 3.77  4.398 5.027 5.655 6.283]
np.cos(y) = 0.70
0.70
0.697


In [117]:
# in-place operation
#x = np.arange(11.)
x *= c
x

UFuncTypeError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

## Multi-Dimensional Arrays

In [86]:
a = np.array([[0, 1, 2, 3], [10, 11, 12, 13]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [87]:
# shape = (rows, columns)
a.shape

(2, 4)

In [88]:
# Element count
a.size # 2*4

8

In [92]:
# Number of Dimensions
a.ndim

2

In [93]:
# Get/Set elements
a[1, 3]  # 2nd row, 4th column

13

In [94]:
a[1, 3] = -1
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, -1]])

In [95]:
a[1]

array([10, 11, 12, -1])

## Array manipulation: Indexing and Slicing

### Slicing Arrays

**var[lower:upper:step]**

If step is not assigned, it is 1 by default.

In [119]:
#            -5  -4  -3  -2  -1
# indices:    0   1   2   3   4
a= np.array([10, 11, 12, 13, 14])

In [120]:
a[1:3]  # last index is not included!

array([11, 12])

In [125]:
# negative indices work also
a[1:-2]

array([11, 12])

In [126]:
a[-3:4]

array([12, 13])

### Omitting indicies

In [128]:
# When you omit the boundary, 
#Python assumes it to be the beginning/end of the list

a[:3]

array([10, 11, 12])

In [129]:
a[-2:]

array([13, 14])

In [132]:
# every other element
a[::2]

array([10, 12, 14])

### Slicing

In [154]:
a = np.array([[0, 1, 2, 3, 4, 5], [10, 11, 12, 13, 14, 15]])
a[0]

array([0, 1, 2, 3, 4, 5])

In [158]:
a[1, 1:2]

array([11])

In [160]:
# stride/step
a[0:2, ::2]

array([[ 0,  2,  4],
       [10, 12, 14]])

In [162]:
# insert with slicing
a = np.array([0, 1, 2, 3, 4, 5])
a[-2:] = [-1, -2]
a

array([ 0,  1,  2,  3, -1, -2])

In [163]:
a[-2:] = 101
a

array([  0,   1,   2,   3, 101, 101])

# Give it a try!
Create the array with the command
**a=np.arange(30).reshape(6,5)**

<img src="figures/00_intro_2_numpy_ex1.png" width="200">

In [196]:
a=np.arange(30).reshape(6,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [197]:
a[-1]

array([25, 26, 27, 28, 29])

In [198]:
a[:, 1]

array([ 1,  6, 11, 16, 21, 26])

In [199]:
a[2:5:2, 2:5:2]

array([[12, 14],
       [22, 24]])

In [200]:
# Arrays from slcing share data with the original array. 
# If you change values in a slice, the values in the original array are
# also changed!
a = np.array([0, 1, 2, 3, 4, 5])
b = a[2:4]
b[0] = 123  # b[0] ==> a[2]
a

array([  0,   1, 123,   3,   4,   5])

In [201]:
# Fancy indexing
a = np.arange(0, 10, 1)
indices = [1, 2, -2]
y = a[indices]
y

array([1, 2, 8])

In [202]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [203]:
# indexing iwth Booleans
mask = np.array([0, 1, 1, 1, 0, 1, 0, 0, 1, 3], dtype = bool)
y = a[mask]
y

array([1, 2, 3, 5, 8, 9])

In [240]:
# Fancy indexing in 2D
a=np.arange(36).reshape(6,6)
print(a)
a[3:, [0, 2, 5]]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


array([[15, 17, 19],
       [20, 22, 24],
       [25, 27, 29]])

# Give it a try!

- Create the array with the command
`a=np.arange(30).reshape(6, 5)`
and extract the elements indicated in red.

- Extract all the number divisible by 3 using a boolean mask.

<img src="figures/00_intro_2_numpy_ex2.png" width="200">

In [246]:
# 1
mask = np.zeros(30, dtype=bool).reshape(6,5)
mask[a%6 == 0] = 1
y = a[mask]
y

array([ 0,  6, 12, 18, 24])

In [245]:
# 2
mask = np.zeros(30, dtype=bool).reshape(6,5)
mask[a%3 == 0] = 1
y = a[mask]
y

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

## Array creation functions

In [250]:
# arange([start], stop, [step], dtype=None)
print(np.arange(4)) # 4 is not included.
print(np.arange(0, np.pi, np.pi/6))

[0 1 2 3]
[0.    0.524 1.047 1.571 2.094 2.618]
[14.1 14.2 14.3 14.4 14.5 14.6 14.7 14.8 14.9 15. ]
[15.1 15.2 15.3 15.4 15.5 15.6 15.7 15.8 15.9 16.  16.1]


In [251]:
# be careful floating point precision.
print(np.arange(14.1,15.1,0.1))
print(np.arange(15.1,16.1,0.1))
print(15.1%1)
print(16.1%1)


[14.1 14.2 14.3 14.4 14.5 14.6 14.7 14.8 14.9 15. ]
[15.1 15.2 15.3 15.4 15.5 15.6 15.7 15.8 15.9 16.  16.1]
0.09999999999999964
0.10000000000000142


In [266]:
# ones(shape, dtype='floa64')
# zeros(shape, dtype='float64')

a =np.ones((2, 3))
print(a.dtype)
b = np.ones((2, 3), dtype='float32')
print(b.dtype)

print(np.zeros((3, 2)))

float64
float32
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [269]:
# identity: n identity array
a = np.identity(4)
print(a)
# empty and fill
# empty(shape, dtype=float64, order='C')
a = np.empty(2)
print(a)

a.fill(3.14)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[5.432e-312 7.291e-304]
[3.14 3.14]


In [271]:
# linspace
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [272]:
# logspace
np.logspace(0, 1, 5)

array([ 1.   ,  1.778,  3.162,  5.623, 10.   ])

## Broadcasting
Broadcasting is a very useful feature of NumPy that will let arrays with differing shapes still be used together. In most cases, broadcasting is faster, and it is more memory efficient than the equivalent full array operation.

In [ ]:
print("Shape of X:", x.shape)
print("Shape of Y:", y.shape)

Now, here are three identical assignments. The first one takes full advantage of broadcasting by allowing NumPy to automatically add a new dimension to the *left*. The second explicitly adds that dimension with the special NumPy alias "np.newaxis". These first two creates a singleton dimension without any new arrays being created. That singleton dimension is then implicitly tiled, much like the third example to match with the RHS of the addition operator. However, unlike the third example, the broadcasting merely re-uses the existing data in memory.

In [ ]:
a = x + y
print(a.shape)
b = x[np.newaxis, :, :] + y
print(b.shape)
c = np.tile(x, (4, 1, 1)) + y
print(c.shape)
print("Are a and b identical?", np.all(a == b))
print("Are a and c identical?", np.all(a == c))

Another example of broadcasting two 1-D arrays to make a 2-D array.

In [ ]:
x = np.arange(-5, 5, 0.1)
y = np.arange(-8, 8, 0.25)
print(x.shape, y.shape)
z = x[np.newaxis, :] * y[:, np.newaxis]
print(z.shape)

In [ ]:
# More concisely
y, x = np.ogrid[-8:8:0.25, -5:5:0.1]
print(x.shape, y.shape)
z = x * y
print(z.shape)