# NumPy
The NumPy package provides the "ndarray" object. The NumPy array is used to contain data of uniform type with an arbitrary number of dimensions. NumPy then provides basic mathematical and array methods to lay down the foundation for the entire SciPy ecosystem. The following import statement is the generally accepted convention for NumPy.

In [2]:
import numpy as np

## Array Creation
There are several ways to make NumPy arrays. An array has three particular attributes that can be queried: shape, size and the number of dimensions.

In [16]:
a = np.array([1, 2, 3])
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)
print(type(a))
print(a.nbytes)  # Return the number of bytes used by the data portion of the array

(3,)
3
1
int64
<class 'numpy.ndarray'>
24


In [15]:
x = np.arange(100)
print(x.shape)
print(x.size)
print(x.ndim)
print(x.dtype)
print(type(x))
print(x.nbytes)

(100,)
100
1
int64
<class 'numpy.ndarray'>
800


In [14]:
y = np.random.rand(5, 80)
print(y.shape)
print(y.size)
print(y.ndim)
print(y.dtype)
print(type(y))

(5, 80)
400
2
float64
<class 'numpy.ndarray'>


## Array Operations

In [78]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])
a + b

array([3, 5, 7, 9])

In [79]:
a*b

array([ 2,  6, 12, 20])

In [80]:
a**b

array([   1,    8,   81, 1024])

## Math functions

In [81]:
# create array from 0. to 10.
x = np.arange(11)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [76]:
# multply entire array by scalar value
c = 2*np.pi/10
print(f'c = {c}') # f strings
print(f'{c*x = }')

y = 0.8
print(f'{np.cos(y) = :.2f}')
print(f'{np.cos(y):.2f}')

c = 0.6283185307179586
c*x = array([0.        , 0.62831853, 1.25663706, 1.88495559, 2.51327412,
       3.14159265, 3.76991118, 4.39822972, 5.02654825, 5.65486678,
       6.28318531])
np.cos(y) = 0.70
0.70


In [77]:
# in-place operation
#x = np.arange(11.)
x *= c
x

UFuncTypeError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

## Multi-Dimensional Arrays

In [86]:
a = np.array([[0, 1, 2, 3], [10, 11, 12, 13]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [87]:
# shape = (rows, columns)
a.shape

(2, 4)

In [88]:
# Element count
a.size # 2*4

8

In [92]:
# Number of Dimensions
a.ndim

2

In [93]:
# Get/Set elements
a[1, 3]  # 2nd row, 4th column

13

In [94]:
a[1, 3] = -1
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, -1]])

In [95]:
a[1]

array([10, 11, 12, -1])

## Array Manipulation
How to change the shape of an array without a copy!

In [ ]:
x.shape = (20, 5)
print(x)

NumPy can even automatically figure out the size of at most one dimension for you.

In [ ]:
y.shape = (4, 20, -1)
print(y.shape)

## Array Indexing

In [ ]:
# Scalar Indexing
print(x[2])

In [ ]:
# Slicing
print(x[2:5])

In [ ]:
# Advanced slicing
print("First 5 rows\n", x[:5])
print("Row 18 to the end\n", x[18:])
print("Last 5 rows\n", x[-5:])
print("Reverse the rows\n", x[::-1])

In [ ]:
# Boolean Indexing
print(x[(x % 2) == 0])

In [ ]:
# Fancy Indexing -- Note the use of a list, not tuple!
print(x[[1, 3, 8, 9, 2]])

## Broadcasting
Broadcasting is a very useful feature of NumPy that will let arrays with differing shapes still be used together. In most cases, broadcasting is faster, and it is more memory efficient than the equivalent full array operation.

In [ ]:
print("Shape of X:", x.shape)
print("Shape of Y:", y.shape)

Now, here are three identical assignments. The first one takes full advantage of broadcasting by allowing NumPy to automatically add a new dimension to the *left*. The second explicitly adds that dimension with the special NumPy alias "np.newaxis". These first two creates a singleton dimension without any new arrays being created. That singleton dimension is then implicitly tiled, much like the third example to match with the RHS of the addition operator. However, unlike the third example, the broadcasting merely re-uses the existing data in memory.

In [ ]:
a = x + y
print(a.shape)
b = x[np.newaxis, :, :] + y
print(b.shape)
c = np.tile(x, (4, 1, 1)) + y
print(c.shape)
print("Are a and b identical?", np.all(a == b))
print("Are a and c identical?", np.all(a == c))

Another example of broadcasting two 1-D arrays to make a 2-D array.

In [ ]:
x = np.arange(-5, 5, 0.1)
y = np.arange(-8, 8, 0.25)
print(x.shape, y.shape)
z = x[np.newaxis, :] * y[:, np.newaxis]
print(z.shape)

In [ ]:
# More concisely
y, x = np.ogrid[-8:8:0.25, -5:5:0.1]
print(x.shape, y.shape)
z = x * y
print(z.shape)